apiVersion: v1
kind: Pod
metadata:
  name: blinker
spec:
  containers:
  - name: blinker
    image: jacopen/blinker
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
    volumeMounts:
      - mountPath: /sys/class/gpio
        name: gpio
      - mountPath: /sys/devices/platform/pinctrl/gpio
        name: device
  nodeSelector:
    kubernetes.io/hostname: k3s-2
  volumes:
  - name: gpio
    hostPath:
      path: /sys/class/gpio
  - name: device
    hostPath:
      path: /sys/devices/platform/pinctrl/gpio
